import type { Metadata } from "next";
import { Alegreya, Playfair_Display, Lora } from "next/font/google";

import "./globals.css";
import { AppProvider } from "@/providers/AppProvider";

const alegreya = Alegreya({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-alegreya",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair-display",
});

const lora = Lora({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alegreya.variable} ${playfairDisplay.variable} ${lora.variable} relative antialiased  overflow-hidden overflow-y-scroll scrollbar scrollbar-thumb-rounded scrollbar-thumb-gray-500 scrollbar-track-gray-200`}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
