import type { Metadata } from "next";
import { Alegreya, Lora } from "next/font/google";

import "./globals.css";
import { AppProvider } from "@/providers/AppProvider";

const alegreya = Alegreya({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-alegreya",
});

const lora = Lora({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alegreya.variable} ${lora.variable} relative antialiased bg-light-bg dark:bg-dark-bg text-light-text dark:text-dark-text  overflow-hidden overflow-y-scroll`}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
